# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e288cde8e5f3bc8c1df3a04075454b16"
name = "sticky card clean"
handle = "sticky-card-clean"
application_url = "https://zsolutions-sticky-cart.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://zsolutions-sticky-cart.onrender.com/auth/callback",
  "https://zsolutions-sticky-cart.onrender.com/auth/shopify/callback",
  "https://zsolutions-sticky-cart.onrender.com/api/auth/callback"
]